### ISSUE TITLE
all PR labels are removed when merging

### ISSUE THREAD

**Issue by jdm** [servo-automation/upstream-wpt-sync-webhook#18]
https://github.com/web-platform-tests/wpt/pull/13511

**Comment by CYBAI** [comment]
also web-platform-tests/wpt#13681

**Comment by jdm** [comment]
Yes, this happens on every PR.

**Comment by CYBAI** [comment]
Maybe the third parameter should be `{ json: ['servo-export'] }` *. (the array should be labels excluding `'do not merge yet'`.)

https://github.com/servo-automation/upstream-wpt-sync-webhook/blob/c4f55fd020006d9ddcd5eadd9ed01a907974a83c/upstream_wpt_webhook/sync.py#L219-L220

Or, we can just remove a label with another endpoint which has the label name in the end of endpoint **?

*: https://developer.github.com/v3/issues/labels/#replace-all-labels-for-an-issue
**: https://developer.github.com/v3/issues/labels/#remove-a-label-from-an-issue
